const REGISTER_FAIL = 'REGISTER_FAIL';
const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const LOGIN_FAIL = 'LOGIN_FAIL';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const CLEAR_FAIL = 'CLEAR_FAIL';
const CLEAR_SUCCESS = 'CLEAR_SUCCESS';
export { REGISTER_FAIL, REGISTER_SUCCESS, CLEAR_FAIL, CLEAR_SUCCESS, LOGIN_FAIL, LOGIN_SUCCESS };