export const GET_FRIENDS_SUCCESS = "GET_FRIENDS_SUCCESS";
export const GET_FRIENDS_FAIL = "GET_FRIENDS_FAIL";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAIL = "SEND_MESSAGE_FAIL";
export const GET_MESSAGE_SUCCESS = "GET_MESSAGE_SUCCESS";
export const GET_MESSAGE_FAIL = "GET_MESSAGE_FAIL";
export const SOCKET_MESSAGE = "SOCKET_MESSAGE";
export const SOCKET_TYPING = "SOCKET_TYPING";
export const RESET_SENDSUCCESS = "RESET_SENDSUCCESS";
export const UPDATE_MESSAGE = "UPDATE_MESSAGE";
export const UPDATE_UNSEEN = "UPDATE_UNSEEN";
export const REMOVE_UNSEEN = "REMOVE_UNSEEN";
export const SET_READ = "SET_READ";

